server:
  port: 8080

spring:
  application:
    name: @project.artifactId@

  datasource:
    continue-on-error: true
    url: jdbc:postgresql://localhost:5432/webchat_db
    platform: postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/chatdb?authSource=admin
